name: Short Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Flake8
      run: flake8 guts scripts tests
    - name: MyPy
      run: mypy guts
    - name: PyTest
      run: pytest
